### PR TITLE
Remove python 2

### LINKED ISSUE #23: Retire Python 2
Python 2 will not be maintained past Jan 1, 2020 (see https://pythonclock.org/). Please remove all Python 2 compatibility and move this package to Python 3 only. 

For conda recipe (including `astroconda-contrib`), please include the following to prevent packaging it for Python 2 (https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html?preprocessing-selectors#skipping-builds): 

``` 
build: 
  skip: true  # [py2k] 
``` 

Please close this issue if it is irrelevant to your repository. This is an automated issue. *If this is opened in error, please let pllim know!*

### PR DESCRIPTION
**Pull request by shannnnnyyy**
This should close #23.

### CODE REVIEW

**Comment by shannnnnyyy** [comment]
@pllim I recently fixed that, but I guess I don't have it set up to rerun tests automatically, so I'll figure out how to get that set up.

I'm actually going to consolidate my changes into one PR and tag you, @nden, and @mdlpstsci for review. I will keep this open until I have that larger one open, then close this.

**Comment by nden** [comment]
@shannnnnyyy Can you rebase this PR on master to pick up p the correct Travis matrix.

**Comment by nden** [comment]
You may also want to add the following in the beginning of `setup.py`.

```
if sys.version_info < (3, 6):
    error = """
    Wfc3tools supports Python versions 3.6 and above.
    """
    sys.exit(error)
```

This will ensure the package will not be installed with Python 2.x

**Comment by shannnnnyyy** [comment]
I'm closing this, will open new PR reflecting similar changes in the future.

**Pull request closed without merging**
