### PR TITLE
Implemented fixes to PSTAT

### PR DESCRIPTION
**Pull request by mdlpstsci**
Removed the specification of image section from the input filename
as this is not Pythonic.  The image section specification is now set using new parameters which are tuples, col_slice and row_slice, that are each defined by two integer values.  As Python is row-major, reversed the use of "column" and "row" parameters when accessing the actual image data to fulfill the expectation of the users.  Enhanced the docstring example.

This PR addresses Git Issue #39.

### CODE REVIEW

**Comment by mackjenn** [comment]
Hi Michele,   Does this mean you removed the capability to plot image sections and that we can now only do slices along a row or column? That is not what we want... In order to identify images with scattered light, we want to plot regions of the detector such as the LHS vs RHS, e.g.

time,lhs=pstat.pstat('ibohbcfgq_ima.fits[100:900,50:250]',  units='rate', stat='midpt')
time,rhs=pstat.pstat('ibohbcfgq_ima.fits[100:900,700:900]',  units='rate', stat='midpt')
plt.plot(time,lhs, label='1',c='b',marker="o",linestyle='None',markersize=5)
plt.plot(time,rhs, label='4',c='r',marker="D",linestyle='None',markersize=5)

Does the updated docstring show how to do this? (I couldn't find it.)

**Comment by mdlpstsci** [comment]
@mackjenn 
Only the way the image section is **_specified_** has changed (in addition to the flip to the axes).  Perhaps I should not use the term "slice".  When I do the following using the unchanged software and then the updated software, I get the same answer.

OLD
`>>> time,lhs=pstat('ibh719grq_ima.fits[100:105,20:25]', units='rate', stat='midpt')
>>> time
array([100.651947,  93.470573,  86.2892  ,  79.107826,  71.926453,
        64.745079,  57.563702,  50.382328,  43.200954,  36.019581,
        28.838205,  21.65683 ,  14.475455,   7.29408 ,   0.112705,
         0.      ])
>>> lhs
array([ 1.82611787,  1.96288013,  1.90146244,  1.84473276,  1.98091388,
        1.8968457 ,  1.7380408 ,  1.76541877,  1.74385285,  2.01260948,
        1.99190307,  1.52315164,  2.22419572,  2.11798906, 31.73974609,
        0.        ])
`

NEW 
>>> time,lhs=pstat('ibh719grq_ima.fits', col_slice=(20,25), row_slice=(100,105), units='rate', stat='midpt')
>>> time
array([100.651947,  93.470573,  86.2892  ,  79.107826,  71.926453,
        64.745079,  57.563702,  50.382328,  43.200954,  36.019581,
        28.838205,  21.65683 ,  14.475455,   7.29408 ,   0.112705,
         0.      ])
>>> lhs
array([ 1.82611787,  1.96288013,  1.90146244,  1.84473276,  1.98091388,
        1.8968457 ,  1.7380408 ,  1.76541877,  1.74385285,  2.01260948,
        1.99190307,  1.52315164,  2.22419572,  2.11798906, 31.73974609,
        0.        ])
>>> 

Is this what you want?  If so, I think I should change the term 'slice' to 'section'?

**Comment by mackjenn** [comment]
Oh great! I got confused by the word slice, but it is clear now that I see your example.

Since people have been using this code in the OLD way, they will now have an error in their software. So I think it would be great if you could explicitly show the change in syntax in readthedocs.  Perhaps something like this?

Original syntax:
pstat('ibh719grq_ima.fits[100:105,20:25]')
Updated (2023) syntax:
pstat('ibh719grq_ima.fits', col_slice=(20,25), row_slice=(100,105))

**Comment by mdlpstsci** [comment]
@mackjenn OK.  I will:

- continue to use the term slice
- update the function signature so row_slice comes before col_slice, and
- update the readthedocs (which I have not done yet)

**Comment by mackjenn** [comment]
Wait, I am confused now!  Columns are the x-values so they should come first.  

The example had the old method with the X and Y flipped so that confused me.  Perhaps both of these changed need to be spelled out .

**Comment by mackjenn** [comment]
Example: To plot the left edge of the detector

Original syntax:  [y1:y2, x1:x2]
pstat('ibh719grq_ima.fits[1:1014,100:300]')

Correcting the row/column order: [x1:x2, y1:y2]
pstat('ibh719grq_ima.fits[100:300,1:1014]')

Implementing tuples for row_slice and column_slice:
pstat('ibh719grq_ima.fits', col_slice=(100,300), row_slice=(1,1014))

**Comment by mdlpstsci** [comment]
Concerns have been addressed in c36a77d update.  The source docstring contains the documentation for the utility and the readthedocs draws on the source docstring.  By definition the source code and the readthedocs have been updated.

**Comment by mdlpstsci** [comment]
@mackjenn @cshanahan1 
Please check the changes are as you expect.  Also, the documentation is now drawn only from the source code docstring and API to eliminate redundancy.

**Comment by mackjenn** [comment]
I'm not sure how to test unofficial code. 
Can @cshanahan1  verify that the regions are working as expected, e.g. by comparing stats on left vs right side of an image with scattered light?

time,lhs=pstat('/grp/hst/wfc3c/mack/ir_flat/TVB/icqtbbbxq_ima.fits', col_slice=(100,300), row_slice=(1,1014)units='rate', stat='midpt'))
time,rhs=pstat('/grp/hst/wfc3c/mack/ir_flat/TVB/icqtbbbxq_ima.fits', col_slice=(700,900), row_slice=(1,1014)units='rate', stat='midpt'))
plt.plot(time,lhs, label='1',c='b',marker="o",linestyle='None',markersize=5)
plt.plot(time,rhs, label='4',c='r',marker="D",linestyle='None',markersize=5)

**Comment by mdlpstsci** [comment]
@mackjenn 
One way to run the new code is to just download the file that you want, pstat.py.   When in the spacetelescope/wfc3tools repo, 

1. Click on the Code menu item at the top-left.  
2. Then look for the file you want (i.e., pstat.py) and click on it.  
3. Click the Raw item at the top-right which will put the file in a raw mode.
4. Then right click in the page and do the "Save Page as" to your working directory with your data.
5. Invoke python, and type the following in the Python session:
6. import pstat (This assumes you did the "Save" as pstat.py)
7. time, counts = pstat.pstat('ibh719grq_ima.fits')

**Comment by mackjenn** [comment]
@mdlpstsci Thank you!  We will have a WFC3 team member test this shortly and report back in this thread.

**Comment by mackjenn** [comment]
WFC3 approves the fix!  Thanks, Michele.

**Pull request merged**
